### ISSUE TITLE
Can't connect / Turn on TV

### ISSUE THREAD

**Issue by jameskirsop** [normen/homebridge-bravia#13]
I'm getting the following error when trying to turn on the TV:
```
Error:  { [Error: connect EHOSTUNREACH 192.168.0.20:80]
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.168.0.20',
  port: 80 }
```

It would seem like the WOL functionality isn't working (or this isn't how it is designed?) @lombi's plugin seemed to be able to turn my Bravia on and off, but I wasn't able to get any of the other features working.

I know that this is the IP address for my TV as I've got a static reservation on my DHCP server, and when I turn it on manually using my remote, I see the list of apps show up in the homebridge CLI output.

**Comment by normen** [comment]
Please see the README on how to enable remote wake-up in your TV.

**Comment by jameskirsop** [comment]
The README is all well and good @normen, except I'm not getting a prompt on the CLI. Hence the query.

**Comment by normen** [comment]
There is no "prompt" on a "CLI" for turning on the TV. If you didn't even manage to set up the PIN yet then its normal that you can't turn on the TV.

**Comment by jameskirsop** [comment]
I'm sorry, I'm a little confused. From your README:
> When you run the plugin for the first time you will have to run homebridge directly from command line as the plugin prompts you for a PIN that the TV will give you.

@Lombi's plugin successfully triggered my TV to provide me with a PIN code to enter when prompted on the command line (CLI). Yours doesn't seem to be doing so. I'm trying to establish why this is, given that you note in the README that your plugin uses some of the work from @Lombi's.

**Comment by normen** [comment]
You seem to be quite confused, yes. You started this issue about turning on the TV and now it turns out you didn't even enter the PIN yet.

If your issue is that the TV doesn't get turned on when you should be prompted for the PIN then simply TURN IT ON YOURSELF. Also ENABLE REMOTE WAKEUP AS OUTLINED IN THE MANUAL.

**Comment by jameskirsop** [comment]
@normen, sorry. I'm not stab you or your project, nor am I trying to waste your time.

I filed this issue because it would seem, from your README, that the project is not working as described. When my TV is on, and I run a fresh install of the plugin from npm, my TV doesn't come up with a PIN that I'm able to enter at the command line.

Remote Wakeup is already enabled.

It did come up with a PIN when I ran the other plugin (which I have since removed from config.json) that I mention above so it wouldn't seem like this is a problem with my TV.

Furthermore, the plugin successfully produces a list of apps installed on the TV.

I'm just trying to explore the possibility of having some assistance with your project and getting it to work in the way you've described with my TV.

**Comment by normen** [comment]
Well sorry, support isn't included in the purchase price ;) This is an issue tracker, there is an issue for the PIN prompt not coming up reliably already.

You getting an app list when you didn't even get a PIN prompt suggests to me that your old "lombi" plugin installation and this one somehow get mixed up and the plugin simply picks up your old PIN file. So if the "cookiepath" points to a location where a file already exists that explains you not getting a PIN prompt.

At any instance it suggests an issue with your setup and not any issue with the plugin that isn't already tracked here and as said, I can't give free support for the software. If you find an actual issue with the wakeup function make a proper issue for it and describe the behavior with the TV on and off and the remote wakeup enabled as well as disabled. Also test what happens when you use the actual on/off function versus simply setting a channel or something. Describe your setup, TV type, yadda, yadda.

Please understand that this isn't some kind of support system for users but its actually a support system for the developers. Its meant to give us meaningful information to solve problems. "Function X doesn't work for me" isn't meaningful information.

Thank you.
