### ISSUE TITLE
TV Disappeared 

### ISSUE THREAD

**Issue by RossiHovitez** [normen/homebridge-bravia#150]
Hi. Installed. Worked fine. Installed another plugin for another device and TV removed. Plug-in is still installed. Please advise

**Comment by normen** [comment]
No idea, impossible to say with so few info. Sounds more like the installation of the other plugin went wrong.

**Comment by RossiHovitez** [comment]
Hi thanks for the reply. I’m new to this. What further information can I provide?  As a wheelchair user reliant on voice this is a really good feature. Thanks.

**Comment by normen** [comment]
That would be homebridge logs, software versions, steps to reproduce coming from a clean install etc.

See, github is a platform where users support developers, not the other way around. Theres a lot of tutorials etc. out there about what kind of information to provide to help out in general. Read through solved issues, maybe even look around on other platforms like reddit what kind of infos people exchange.

Otherwise, consider your note here about "TV disappearing when other plugin is installed" help enough, if theres more people coming in with this issue we'll know more. Thanks.

**Comment by RossiHovitez** [comment]
![ACEF6EEC-7CF8-41DF-9F4C-104FD76F0285](https://user-images.githubusercontent.com/81195491/112302299-d31dee00-8c92-11eb-8441-3835b3b3c072.jpeg)

**Comment by RossiHovitez** [comment]
[22/03/2021, 22:23] [BraviaPlatform] Can't load sources for extInput:scart

[22/03/2021, 22:23] [BraviaPlatform] TV response:

[22/03/2021, 22:23] [BraviaPlatform] {"error":[3,"Illegal Argument"],"id":13}

**Comment by normen** [comment]
No problem there. Just disable debug mode if you don't want to see the message that your TV has no scart connectors.
