### ISSUE TITLE
Split into two separate accessories?

### ISSUE THREAD

**Issue by nikf86** [normen/homebridge-bravia#171]
I really appreciate your plug in! My TV is homekit compatible but your plug in is way more reliable!

However, I run into problems when I try to make automations most likely because the HDMI input is dynamic. More specifically, if I run a homekit automation where the TV is set to On and HDMI 2 problems arise when the TV was powered off while on HDMI 1! I even tried a combination by using both the TV's native homekit and your plug in at the automation but it is still problematic.. 

Do you think you can split the accessory into teo separate ones? One for the on/ off irrespectively of the HDMI input active at the time and the second one to set new HDMI input?

**Comment by normen** [comment]
Not really, the channel list is only available from the TV device itself.

But I guess the issue you're having is more due to how the Home app works, really. It basically decides what parameters of the device get stored in the scene/automation. When I first played with this it would usually only store the "main" parameter and then the parameters that I would change _while creating the scene_. So for a lamp it would store the on/off state but not the color, it would only store the color when I change it when creating the scene.

Otherwise, if you can't make the Home app do what you want (only store the on/off state) - the Eve app allows a bit more control when creating automations (including conditions etc.), maybe try using that to make the automation?
