### ISSUE TITLE
Channels are not working after homebridge update

### ISSUE THREAD

**Issue by asenovb** [normen/homebridge-bravia#23]
Hello Normen,

First of all I would like to express my gratitude to you for developing this plugin. Thank you!

I had to update my homebridge (running on Rasp PI) because the previous version was unstable with iOS 11. After reinstalling everything and setting it up the Channel switch is not working anymore. On/off feature along with volume works fine.

Is there a known issue? Can you point me in which direction should I look for the problem if it is not related to the Homebridge update?

Small addition is that if I add an app and create scene it is working fine oO

EDIT: Changing the TV Source to DVBT seems to solve only partially the issue. I can switch up to channel 50, 51 is not working.

Regards!

**Comment by normen** [comment]
No I can't help you, sorry. I don't have time to do support for this free software. I can only tell you that it rather sounds like there isn't an issue per se but it's some setting or you just expect something to happen but do the other. Nothing essential changed in the plugin since it was released.
