### ISSUE TITLE
Homebridge not booting if TV is not connected

### ISSUE THREAD

**Issue by benzman81** [normen/homebridge-bravia#42]
I turn off all my standby devices during night. Now, as I restart home bridge via schedule in the night, all accessories become unavailable at that point as soon as your plugin is activated.
The error in the log is:

`2019-04-14 02:01:39 | stdout | port: 80 }-- | -- | --`
`2019-04-14 02:01:39 | stdout | address: '10.0.1.7',`
`2019-04-14 02:01:39 | stdout | syscall: 'connect',`
`2019-04-14 02:01:39 | stdout | code: 'EHOSTUNREACH',`
`2019-04-14 02:01:39 | stdout | errno: 'EHOSTUNREACH',`
`2019-04-14 02:01:39 | stdout | at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)`
`2019-04-14 02:01:39 | stdout | `
`[4/14/2019, 2:01:39 AM] [BraviaPlatform] Error:  { Error: connect EHOSTUNREACH 10.0.1.7:80`

Any chance you can handle such an environment? For now I need to turn your plugin off.

**Comment by normen** [comment]
Not really. The thing is, when HomeBridge boots up it gets the name of all Accessories from the plugins. As each channel is an accessory and the Bravia plugin gets the channel names from the actual TV it needs to be on to report the accessories correctly. If it cannot reach the TV at that moment it won't report an accessory list and the HomeBridge server won't start completely.

And this is by design - because all automation and room assignment for those devices will be lost (by HomeKit) if the HomeBridge server starts without them. Next time the TV is on an the server starts you would get a TV without an assigned room - as if it was a new device.

So for your situation - simply make sure the TV can be reached by the plugin when the HomeBridge server starts up. I have the same for my other automation systems - the heating, light bridges etc. - they have to be accessible when the HomeBridge server starts. Basic server 101.

**Comment by Philseneer** [comment]
But my homebridge is aborting this way.
What can I do instead of leaving my TV on 24/7?

**Comment by normen** [comment]
Please read my answer again, not 24/7, only when STARTING the homebridge server.

**Comment by Philseneer** [comment]
Correct. In my case the system is starting every night. 
But hat helps me. Thanks!

**Comment by benzman81** [comment]
Does it have to be „on“ or is standby enough? And will it turn „on“ tv for registration?

**Comment by benzman81** [comment]
And wouldnt it be possible to do some caching?

**Comment by normen** [comment]
Again, this isn't a support forum, this is a bug tracker. This is not where I help you, this is where you are supposed to help me.

So for your first question - why don't you try for yourself? I don't know how your TV will react. This is DIY land - so DIY. And for question two - you can send a PR for caching the channel names if you want, I'll have a look. Storing data in HomeBridge is always ugly though, as theres no built-in way to store data - that sonycookie is ugly enough.

Really, how this is supposed to work is that your bridge knows what devices it can report to HomeKit when it registers with HomeKit - in our case thats when the server boots. So ideally you'd have one Raspi per TV or have the TV running the HomeBridge service and they'd only even announce themselves when they're available and ready.

**Comment by creedda** [comment]
If anyone else wants to know,

I seem to have mostly solved this issue by adding the following line to my "/etc/systemd/system/homebridge.service" file under the [Service] stanza and running "systemctl daemon-reload"

_ExecStartPre=/usr/bin/wakeonlan [Mac address of TV]_

I have a KDL-50W900A so mileage may vary. But basically any command you can run to start your TV from the command line can be used instead. This also leaves your TV on post Homebridge boot, so I rely on my TV eco features to turn the tv off if it is getting no signal after a while. My use case is mainly upgrades and pi restarts so I am also not rebooting all the time.

Just wanted to share.

**Comment by mkellsy** [comment]
Server 101?
DIY?

Ok fork code. Fix code, so it doesn't crash HB. Then maybe add a feature to handle the error and connect to the TV when it becomes available.

CSC 101!

**Comment by normen** [comment]
> Server 101?
> DIY?
> 
> Ok fork code. Fix code, so it doesn't crash HB. Then maybe add a feature to handle the error and connect to the TV when it becomes available.
> 
> CSC 101!

Awaiting PR :)

**Comment by normen** [comment]
> Server 101?
> DIY?
> 
> Ok fork code. Fix code, so it doesn't crash HB. Then maybe add a feature to handle the error and connect to the TV when it becomes available.
> 
> CSC 101!

Any news?

**Comment by egnerfl** [comment]
First of all thanks for creating this awesome plugin, I really appreciate your work @normen !

Is there a technical reason why the device "TV" can't be shown as unreachable in the "unreachable state" just like light bulbs can be shown as unreachable in homekit? 

If not, I can try to open a PR with that behavior. 

The background is that every time my wifi access point restarts my TV doesn't reconnect automatically and homebridge crashes. Since I'm using a dockerized homebridge setup I just have a second dedicated homebridge instance running just for the bravia integration 🙈

**Comment by normen** [comment]
> First of all thanks for creating this awesome plugin, I really appreciate your work @normen !
> 
> Is there a technical reason why the device "TV" can't be shown as unreachable in the "unreachable state" just like light bulbs can be shown as unreachable in homekit?
> 
> If not, I can try to open a PR with that behavior.
> 
> The background is that every time my wifi access point restarts my TV doesn't reconnect automatically and homebridge crashes. Since I'm using a dockerized homebridge setup I just have a second dedicated homebridge instance running just for the bravia integration 🙈

Sure, you'd have to add dynamic accessory support as outlined in the new platform example:
https://github.com/nfarina/homebridge/blob/master/example-plugins/homebridge-samplePlatform/index.js

But thats basically a rewrite of the plugin, plus the PIN entry should be done through dynamic accessory configuration requests as well then. In any case it will require everybody using this plugin to re-configure their TVs in HomeKit as they will be completely new accessories for HomeKit.

So yeah, PR is welcome if you want to take a shot, I probably won't add dynamic support to this plugin anytime soon, for some of the other plugins I continued it makes more sense.

P.S. As a hint, if you don't configure any inputs or channels then the TV won't bee needed during bootup. So if you don't switch any channels using HomeKit then just leave them out. (I found I liked the idea but never actually used it except for a stupid "turn on the fireplace" scene I never use either).

**Comment by normen** [comment]
There, 2.0 uses the dynamic accessory model. Good work @all

**Comment by Soldiiier** [comment]
Does “Dynamic accesessory model mean that HB hang if the TV is unreachable when booting?

**Comment by normen** [comment]
No
