### ISSUE TITLE
Siri can Increase or decrease Volume ?

### ISSUE THREAD

**Issue by fennec622** [normen/homebridge-bravia#61]
First thanks for this plugin

Do you know if Siri can Increase or decrease Volume ?

Thanks

**Comment by normen** [comment]
No, apparently that doesn't work with the new iOS12 TV support because the device is expected to be an AirPlay receiver as well and be controlled that way.. Thats (if at all possible) out of the scope of this plugin though. Technically the plugin supports setting the volume directly though, maybe you're lucky with making a scene in the Eve HomeKit app, it usually supports more parameters than Apples own Home app.

**Comment by fennec622** [comment]
ok thanks
i do volume change with lightbulb level  and mqtt
it's ok just want to know if it's possible with television 

Again thanks
