### ISSUE TITLE
TV Requiring PIN Again

### ISSUE THREAD

**Issue by Soldiiier** [normen/homebridge-bravia#96]
I am not sure what the cause is, but so far (in the space of about 2-3 weeks) it has happened 3 times, where homebridge is asking for a Pin to be entered to paid.
On the Sony's settings>remote devices, the old devices are still present (ie each entering of a pin creates a new 'remote'.

One of my earlier errors was: 
[BraviaPlatform] Error:  Error: connect ENETUNREACH 10.1. 
Even though the TV has been given a static IP.

**Comment by normen** [comment]
In the older versions you could create a TV in HomeKit once and every TV you created in that same HomeBridge instance would use the same ID. That is not the case anymore since 2.1.9 where every new instance of a TV in HomeKit has a new ID.

Meaning if you delete your accessory cache or rename the TV or do anything else that makes the accessory "new" for HomeKit it will prompt you for a new PIN.

**Comment by Soldiiier** [comment]
Thanks for the response. So me “clearing accessor cache” in home lbridge caused this?
Thanks.

**Comment by normen** [comment]
If you did that then yes, that would be expected behavior.
